import Head from "next/head";
import Image from "next/image";
import header from "../assets/images/header.jpg";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Texas Chicken®</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image width={1950} height={700} quality={70} src={header} alt="header" />
    </div>
  );
}
